### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by moreje** [BIC-MNI/minc-tools#86]
Hello,
I try to build minc-tools (develop branch) on a new Ubuntu 18.10 system.
Cmake outputs the following error:
NIFTI_DIR                        NIFTI_DIR-NOTFOUND

I can't find where/how to define this NIFTI-DIR option
thanks for your help

**Comment by gdevenyi** [comment]
Hi,

Please provide your configure command, outputs and error logs.

**Comment by moreje** [comment]
I only have this warning at the configure step:
```
CMake Deprecation Warning at CMakeLists.txt:24 (CMAKE_POLICY):
   The OLD behavior for policy CMP0026 will be removed from a future version
   of CMake.

   The cmake-policies(7) manual explains that the OLD behaviors of all
   policies are deprecated and that a policy should be set to OLD only under
   specific short-term circumstances.  Projects should be ported to the NEW
   behavior and not rely on setting a policy to OLD.

```
and then:

```
BUILD_TESTING                    OFF                                                                    
 CMAKE_BUILD_TYPE                 Release                                                                
 CMAKE_INSTALL_PREFIX             /usr/local/MINC/minc-tools-dev                                         
 LIBMINC_DIR                      /usr/lib/x86_64-linux-gnu/cmake/LIBMINC                                
 NIFTI_DIR                        NIFTI_DIR-NOTFOUND                                                     
 jconfig_dir                      /usr/include/x86_64-linux-gnu
```

**Comment by vfonov** [comment]
I suggest building https://github.com/BIC-MNI/minc-toolkit-v2 or https://github.com/BIC-MNI/minc-toolkit

**Comment by moreje** [comment]
it is what I used to do (minc-toolkit-v2) .... but I need some fixes/updates recently pushed on minc-tools by R. Vincent...(and I also facing building issues with minc-toolkit-v2 on a new Ubuntu PC)

**Comment by gdevenyi** [comment]
You can clone minc-toolkit-v2 and selectively update the commit hash of the minctools subproject to pull in the new fixes, rather than trying to selectively compile minctools.

If you want to go this path, you will need to download/build/install niftilib, or point the minctools config to an existing minc-toolkit-v2 build of niftilib.

**Comment by moreje** [comment]
thank you, I will try that...
any idea on how to fix:
`OpenBLAS_DIR                     OpenBLAS_DIR-NOTFOUND   `
when trying to build minc-toolkit-v2 ? I thought openBlas should be built with minc-toolkit?
thank you

**Comment by gdevenyi** [comment]
Also sent via email....

You're hitting this bug:
https://github.com/BIC-MNI/minc-toolkit-v2/issues/72

Since I'm not sure of the fix for this bug yet, I haven't had time to investigate, what you can do is avoid it by:
- clear your build directory
- Use the non-interactive cmake settings as example here:
https://github.com/BIC-MNI/build_packages/blob/master/build_v2.sh#L45-L73

In particular what you need is -DMT_BUILD_OPENBLAS:BOOL=ON

You may be able to add just that option to a "ccmake" command but I haven't tested.

**Comment by moreje** [comment]
thank you! let's try!
